language:
- swift
osx_image:
- xcode13.3
script:
- travis_wait 90 fastlane local_appstore
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_0565cb21f477_key -iv $encrypted_0565cb21f477_iv
  -in .autodeployment.sh.enc -out .autodeployment.sh -d
- chmod +x .autodeployment.sh
- ". ./.autodeployment.sh"
- bundle install
